### ISSUE TITLE
GET /static/scripts/swiper.min.js.map HTTP/1.1" 404 1714

### ISSUE THREAD

**Issue by phjppo0918** [C-B-U/cbums#10]
해당 map 를 찾을 수 없다고 떠서 swiper.min.js 에서 맨 아리에 `sourceMappingURL=swiper.min.js.map` 부분의 주석처리를 지웠는데, 혹시 주석처리하신 이유가 있으신가요??
@rabbit-22

**Comment by rabbit-22** [comment]
엇 js는 다운 받고나서 건드리지 않았어요!
