### ISSUE TITLE
Execution failed for task ':installReact' 문제

### ISSUE THREAD

**Issue by SunWooBang** [C-B-U/cbums#125]
프로젝트 실행 시(ctrl+shift+f10) 발생하는 문제

오류 메시지
Execution failed for task ':installReact'.
> A problem occurred starting process 'command 'yarn.cmd''

**Comment by phjppo0918** [comment]
오류 메세지가 위 내용말고는 없었나요???

**Comment by phjppo0918** [comment]
npm 버전이 지금 어떻게 될까요??

**Comment by SunWooBang** [comment]
추가적 메시지

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

 + npm 버전은 8.1.0 입니다!

**Comment by phjppo0918** [comment]
제가 알기로는 yarn을 global로 설치해야 하는걸로 알고있는데 설치 하셨나요??
