### ISSUE TITLE
비밀번호 찾기 페이지 css 트레쉬 코드 처리

### ISSUE THREAD

**Issue by phjppo0918** [C-B-U/cbums#2]
중간에 삭제해야할 코드라고 주석이 있는데, 어느 범위까지 삭제를 해야할지 몰라서 일단은 그냥 뒀어요! 이슈 보시면 직접 코드 삭제하시고 커밋해주세요~

**Comment by phjppo0918** [comment]
@rlawldbs0911

**Comment by rlawldbs0911** [comment]
넵!
